# Generated by Django 3.2.15 on 2022-09-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('todos', models.ManyToManyField(blank=True, related_name='todos', to='todo.Todo')),
            ],
        ),
    ]
